### ISSUE TITLE
HTTPS certificate expired

### ISSUE THREAD

**Issue by tyxchen** [BSVino/docs.gl#106]
It appears that the HTTPS certificate for docs.gl expired on 19 August. Users visiting https://docs.gl will see a message similar to this:

![image](https://user-images.githubusercontent.com/7224751/132953749-8a22cbcf-5c57-4edb-b7f0-e208659fcd12.png)

**Comment by BSVino** [comment]
Thanks for bringing it to my attention. Should be fixed now.
