### ISSUE TITLE
Active command category not automatically expanding on page-load

### ISSUE THREAD

**Issue by jacquesh** [BSVino/docs.gl#120]
When the page loads on the docs for a particular function, I see the command category list down the left-side is meant to automatically expand to show the currently-selected function but this doesn't appear to work at the moment (I tested on Firefox, Edge & Chrome).

The little arrow next to the category does indicate that it intended to be expanded though, as shown here:
![image](https://user-images.githubusercontent.com/4639662/181040126-90b4359b-5495-4f91-94ec-4ab4dcdf56fa.png)

This isn't the end of the world but not having to collapse and re-expand the category each time I want to go to a related function would be a definite quality-of-life improvement.

I did a small amount of fiddling with the code and it seems this is an issue with the calls to bonsai. If I increased the timeout it worked and if I replaced the inlined `expand` call (explained by the nearby comment to intend to avoid the expand animation) or added a bonsai `update()` call then it also worked (but was animated). I agree that not animating on page-load would be better than animating, but personally I think animating and expanding is better UX than not expanding.

Sadly I'm not well-versed enough in frontend dev to have any good ideas on how to make it both expand and not animate without completely changing the way the category tree is constructed in the DOM!

**Comment by BSVino** [comment]
Yup this annoyed the hell out of me and I too am not well-versed in frontend dev so I had to give it up. If you want to submit a pull request for your change it sounds like a definite improvement and we can try it out!
