### ISSUE TITLE
Search input field doesn't autofocus

### ISSUE THREAD

**Issue by Shimmen** [BSVino/docs.gl#31]
This happens for me using Google Chrome 44 (full version name 44.0.2403.125 m) on Windows 8.1. As far as I know the "autofocus" attribute, which exists on the search field tag, should work on this version of Chrome.

**Comment by BSVino** [comment]
I got a patch for it already but I just haven't rebuild it and put it up. I'll do that now, check back again in a bit and let me know if it's still bad.

**Comment by BSVino** [comment]
Alright it's done, and it seems to work for me in Safari.

**Comment by Shimmen** [comment]
Yes, it works great!
