### ISSUE TITLE
Error in vertex array example?

### ISSUE THREAD

**Issue by ndevenish** [BSVino/docs.gl#32]
Noticed on es3/glDrawArrays, The vertex array example, https://github.com/BSVino/docs.gl/blob/master/html/examples/vertexarray_draw.htm#L11
calls:

    glDrawArrays(GL_TRIANGLES, 0, vertex_data);

but also states that `// vertex_data is a float*, 3 per vertex`, where as far as I can tell this function always takes a GLint - so it should probably be a count of the vertex data instead. (I do not know the context of the examples, so cannot give a precise suggestion, assuming that this is a real error).

**Comment by BSVino** [comment]
Nope, I think you're correct, it's an error. I'll fix it.
