### ISSUE TITLE
"Unexpected text node" on `glBufferData` page

### ISSUE THREAD

**Issue by kylewlacy** [BSVino/docs.gl#37]
Tested in Chrome 46.0.2486.0-dev (Mac OS X 10.10.5).

On the [OpenGL ES2](http://docs.gl/es2/glBufferData), [OpenGL 2](http://docs.gl/gl2/glBufferData), and [OpenGL 3](http://docs.gl/gl3/glBufferData) versions of the `glBufferData` docs page, the following snippet appears under the "notes" section:

!["Unexpected text node: 'be a multiple of'"](https://cloud.githubusercontent.com/assets/1362179/9565833/3a528840-4e9d-11e5-8fdc-cbb37d9236f6.png)

(Some other text actually briefly appears on the page after refreshing. No errors appear in the Chrome inspector console log.)

**Comment by reima** [comment]
https://github.com/BSVino/docs.gl/pull/35 should have fixed this, but it seems it hasn't been pushed to the website yet.

**Comment by kylewlacy** [comment]
@reima Oh, whoops, didn't see the PR before posting!

**Comment by BSVino** [comment]
Sorry about that. Building the site now, it should be live with updates soon.
