### ISSUE TITLE
textureGather's description is wrong

### ISSUE THREAD

**Issue by NicolBolas** [BSVino/docs.gl#48]
[The website says this](http://docs.gl/sl4/textureGather):

    vec4(Sample_i0_j1(P, base).comp,
         Sample_i1_j1(P, base).comp,
         Sample_i1_j0(P, base).comp,
         Sample_i0_j1(P, base).comp);

But the GLSL specification says this:

    vec4(Sample_i0_j1(P, base).comp,
         Sample_i1_j1(P, base).comp,
         Sample_i1_j0(P, base).comp,
         Sample_i0_j0(P, base).comp);

Note the last one, with the 0,0 i,j value.

This mistake is also in the `textureGatherOffset` and `textureGatherOffsets` functions.

**Comment by BSVino** [comment]
Care to make a PR?

**Comment by leumasme** [comment]
Why is this issue still open if the closing PR has been merged?
