### ISSUE TITLE
glUnmapBuffer automatically redirects to glMapBuffer

### ISSUE THREAD

**Issue by chrisyeshi** [BSVino/docs.gl#49]
http://docs.gl/gl3/glUnmapBuffer automatically redirects to http://docs.gl/gl3/glMapBuffer.

**Comment by BSVino** [comment]
glUnmapBuffer is also described on that page.

**Comment by chrisyeshi** [comment]
I see. It's confusing especially the glUnmapBuffer page shows up for a split second before redirected.

**Comment by BSVino** [comment]
Yea it's a client-side redirect because I don't have any server-side processing on the site. I could move Unmap to its own page but I don't want to change the pages too much so that merging upstream changes is easier.
