### ISSUE TITLE
www.docs.gl shows content from buygamesnotsocks.com

### ISSUE THREAD

**Issue by Pokechu22** [BSVino/docs.gl#68]
Going to http://www.docs.gl gives the same 5 for $5 bundle content as going to http://www.buygamesnotsocks.com.  The actual content is only served on http://docs.gl.

Presumably some kind of server misconfiguration, as it seems like both of those sites are hosted on the same IP.

Reported on the LWJGL slack originally.

**Comment by BSVino** [comment]
Thanks. All subdomains of docs.gl now serve docs.gl. Fuck if I know how to use nginx good enough to make them redirect, but this will work fine for now.
